version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: 'reddit'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - database_data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: 'cluster_cookie'
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'
      RABBITMQ_DEFAULT_VHOST: '/'

  consumer:
    build: ./src/consumer/exec
    restart: on-failure
    links:
      - rabbit
      - db
    environment:
      AMQP_DEFAULT_BROKER: 'amqp://admin:admin@rabbit'
      AMQP_DEFAULT_EXCHANGE: 'amqp.fanout'
      POSTGRES_CONN: 'host=db port=5432 user=admin password=admin dbname=reddit sslmode=disable'
    depends_on:
      - rabbit
      - db

  producer:
    build: ./src/events/exec
    restart: on-failure
    links:
      - rabbit
    environment:
      AMQP_DEFAULT_BROKER: 'amqp://admin:admin@rabbit'
      AMQP_DEFAULT_EXCHANGE: 'amqp.fanout'
      GRAW_BOT_AGENT: 'localbot.agent'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rabbit

volumes:
  database_data:
    driver: local
